### ISSUE TITLE
Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by StarNeit** [trufflesuite/truffle-hdwallet-provider#14]
Error: Invalid JSON RPC response: ""
4|bwcoin_p |     at Object.InvalidResponse (/var/www/xxx/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
4|bwcoin_p |     at XMLHttpRequest.request.onreadystatechange (/var/www/xxx/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
4|bwcoin_p |     at XMLHttpRequestEventTarget.dispatchEvent (/var/www/bwcoin/node_modules/xhr2/lib/xhr2.js:64:18)
4|bwcoin_p |     at XMLHttpRequest._setReadyState (/var/www/bwcoin/node_modules/xhr2/lib/xhr2.js:354:12)
4|bwcoin_p |     at XMLHttpRequest._onHttpResponseEnd (/var/www/bwcoin/node_modules/xhr2/lib/xhr2.js:509:12)
4|bwcoin_p |     at IncomingMessage.<anonymous> (/var/www/bwcoin/node_modules/xhr2/lib/xhr2.js:469:24)
4|bwcoin_p |     at emitNone (events.js:91:20)
4|bwcoin_p |     at IncomingMessage.emit (events.js:185:7)
4|bwcoin_p |     at endReadableNT (_stream_readable.js:974:12)
4|bwcoin_p |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
4|bwcoin_p |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
4|bwcoin_p | [nodemon] app crashed - waiting for file changes before starting...

I am minting tokens using hdwallet-provider and infura, but i am receiving this issue.
How can I avoid this interruption?

**Comment by seita-uc** [comment]
I solved this problem by correcting the url set in HDWalletProvider in truffle.js file. If any one of HDWalletProvider has wrong url, the error occurs. I hope this works for you too.

**Comment by rayeaster** [comment]
will infura endpoint expire ? how to verify if the infura link is still valid

**Comment by rayeaster** [comment]
got same problems, seems not the issue about truffle.js urls. Any clue?

**Comment by GarryPlays** [comment]
Getting this issue all the time. Using Infura, node, no truffle. Seems a timeout issue. Impossible to catch :(

**Comment by Spaider15** [comment]
@zachlysobey Hello, i just wonder, why they need to start pooling at all?
for example, if i just using infura url as provider for web3, web3 will send request to enfura when i will ask for it, getBalance, or deploy smart contract etc. And i will not receive this error.

**Comment by gianchandania** [comment]
Faced the same issue. Getting this error when trying to run the write function on Ropsten-Infura testnet. Can anyone please suggest some solution to this. Its urgent. Thanks in advance.

**Comment by haidoan** [comment]
anyone found the solution yet? I use truffle with kovan infura

**Comment by GarryPlays** [comment]
catch crash, retry .. I know, it's that sad

**Comment by ericmuyser** [comment]
Gonna see if I can dig into the providers and stop the polling

**Comment by theone3nu** [comment]
Any update on this

**Comment by superrsage** [comment]
If anyone wants to stop polling, use `hdWalletProvider.engine.stop()`

**Comment by mlekena** [comment]
Make sure the link/URL to the blockchain you are sending messages too is valid as well. That was my issue. Once I corrected it, it worked. (I had the wrong Infura security token)
