### ISSUE TITLE
Error while installing NPM package

### ISSUE THREAD

**Issue by TheRyanMiller** [trufflesuite/truffle-hdwallet-provider#26]
```
make: Entering directory '/home/ryan/Desktop/react_attendance/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
make: g++: Command not found
copied_files.target.mk:22: recipe for target 'Release/obj.target/copied_files.node' failed
make: *** [Release/obj.target/copied_files.node] Error 127
make: Leaving directory '/home/ryan/Desktop/react_attendance/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-37-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ryan/Desktop/react_attendance/node_modules/scrypt
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN The package dotenv is included as both a dev and production dependency.
npm WARN The package web3 is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌────────────────────────────────────────────────────────┐
│                npm update check failed                 │
│          Try running with sudo or get access           │
│          to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/ryan/.config │
└────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ryan/.npm/_logs/2018-04-04T13_52_35_094Z-debug.log

```

**Comment by zachlysobey** [comment]
With this kinda error its useful to include certain info like: node version, npm version, and OS to help understand what might be happening.

This looks like a similar issue and might be of help?

> https://github.com/facebook/react/issues/3744
