### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by marcusnguyen** [trufflesuite/truffle-hdwallet-provider#28]
I was following this tutorial http://truffleframework.com/tutorials/using-infura-custom-provider and i tried installs windows build tools, and still getting the same error.

C:\WINDOWS\system32>npm install truffle-hdwallet-provider

> scrypt@6.0.3 preinstall C:\WINDOWS\system32\node_modules\scrypt
> node node-scrypt-preinstall.js

> keccak@1.4.0 install C:\WINDOWS\system32\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild C:\WINDOWS\system32\node_modules\keccak
> node-gyp rebuild

C:\WINDOWS\system32\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\keccak
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dngu899\AppData\Roaming\npm-cache\_logs\2018-04-22T09_05_58_429Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> scrypt@6.0.3 install C:\WINDOWS\system32\node_modules\scrypt
> node-gyp rebuild

C:\WINDOWS\system32\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\WINDOWS\system32\node_modules\scrypt\build\..\scrypt\win\include\config.h
MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\scrypt
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dngu899\AppData\Roaming\npm-cache\_logs\2018-04-22T09_05_59_944Z-debug.log

**Comment by zachlysobey** [comment]
It seems likely that this is just something messed up with your local dev environment.

Some things I might try:

 - wiping away `node_modules` and trying again
 - different version of `npm` / `node`
 - `npm cache clean`
- Delete your $HOME/.node-gyp directory

If you google around for "npm issues" and "node-gyp" there are lots of GH issues with similar problems, that might provide help debugging and resolving this:

For example:
https://github.com/nodejs/node-gyp/issues/809

**Comment by kopbeen** [comment]
Good day.

I am experiencing the same error as **marcusnguyen**. I've tried do delete the **node-gyp** folder and ran the `npm cache clean `command. How do you wipe away the `node_modules `? 

After doing the above, I do get a different error message now: 

_npm WARN deprecated truffle-hdwallet-provider@1.0.17: WARNING: This package has been renamed to @truffle/hdwallet-provider.

> sha3@1.2.3 install C:\Windows\System32\node_modules\sha3
> node-gyp rebuild


C:\Windows\System32\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: win-x86/node.lib local checksum 09768da6d90c2a596782359944a641fff38ff44a3d141f21ead1d557b386fabd not match remote 459095d9bd9dc4e2d12c4284e6fc5bdc78eec8181c8327c57876499b002a59fd
gyp ERR! stack     at deref (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:270:20)
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:358:24)
gyp ERR! stack     at Request.emit (events.js:203:15)
gyp ERR! stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1083:12)
gyp ERR! stack     at Object.onceWrapper (events.js:286:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:203:15)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1145:12)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\System32\node_modules\sha3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\System32\package.json'
npm WARN System32 No description
npm WARN System32 No repository field.
npm WARN System32 No README data
npm WARN System32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above._

Any help will be greatly appreciated. 

Also, my npm is version 6.9.0 and my node is 10.16.3 
(Windows 10 PC)

**Comment by LizanLycan** [comment]
Same error here:
OS: Windows 10
Node Js Verison: 12.13.0
NPM Version: 6.12.1
Visual Studio Build Tools: 2017
windows-build-tools Version: windows-build-tools@5.2.2


> It seems likely that this is just something messed up with your local dev environment.
> 
> Some things I might try:
> 
> * wiping away `node_modules` and trying again
> * different version of `npm` / `node`
> * `npm cache clean`
> * Delete your $HOME/.node-gyp directory
> 
> If you google around for "npm issues" and "node-gyp" there are lots of GH issues with similar problems, that might provide help debugging and resolving this:
> 
> For example:
> [nodejs/node-gyp#809](https://github.com/nodejs/node-gyp/issues/809)

Well, it's worked for me, my environment with error:
- OS: Windows 10
- Node Js version: 12.3
- NPM Version: 6.12

The solution was downgrade the Node js version to:
- Node Js version: 11.15
(https://nodejs.org/download/release/)

And all compile and build perfectly!
