### ISSUE TITLE
awaitCurrentBlock  - SyntaxError: Unexpected indetifier

### ISSUE THREAD

**Issue by Saurabh1402** [trufflesuite/truffle-hdwallet-provider#37]
~/node_modules/eth-block-tracker/src/index.js:38
  async awaitCurrentBlock () {
             ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/saurabh/Desktop/Work/IDE/Blockchain/truffle/First Token/node_modules/web3-provider-engine/index.js:4:25)

**Comment by Saurabh1402** [comment]
error is showing for awaitCurrentBlock

**Comment by cgewecke** [comment]
@Saurabh1402 Are you able to upgrade to Node 8? It looks like eth-block-tracker uses the newer async/await syntax that's standard with Node's current recommended version.

**Comment by JoelAH** [comment]
Any solution for this yet? Having same issue

**Comment by cgewecke** [comment]
@JoelAH What version of node are you using?

**Comment by JoelAH** [comment]
7.4 @cgewecke

**Comment by cgewecke** [comment]
@JoelAH Node's latest stable version is 8. Please upgrade if possible  - `async / await` syntax is fully supported in that version. It's partially supported in Node 7 (more detail [here](https://stackoverflow.com/questions/41756622/using-async-await-in-node-7-4)).

We recently had to upgrade one of the wallet's dependencies for security reasons and it uses this new promise syntax under the hood. Will modify the README to reflect this new requirement.

**Comment by JoelAH** [comment]
Ok thanks
