### ISSUE TITLE
Ropsten Infura + Truffle + truffle-hdwallet-provider. Issue while performing the write function in the smart contract deployed on Ropsten Network

### ISSUE THREAD

**Issue by gianchandania** [trufflesuite/truffle-hdwallet-provider#43]
When I am trying to call a Write function of the smart contract deployed on the ropsten network using truffle, I get error Invalid JSON RPC response: "" . The Read functions are working fine. I have read that same issue has been reported here but no solution is provided for that. 

Truffle Version: Truffle v4.1.8 (core: 4.1.9)
Solidity v0.4.24 (solc-js)
truffle-hdwallet-provider: 0.0.5

Can you please help with what is causing this issue and how to resolve it. It is bit urgent.Thanks.

**Comment by xinbenlv** [comment]
Also mentioned in #45 seems similar

**Comment by xinbenlv** [comment]
Here is my XMLHttpRequest that I print out from 
```
invalid reponse raw result XMLHttpRequest {
  onloadstart: null,
  onprogress: null,
  onabort: null,
  onerror: null,
  onload: null,
  ontimeout: [Function],
  onloadend: null,
  _listeners: {},
  onreadystatechange: [Function],
  _anonymous: undefined,
  readyState: 4,
  response: null,
  responseText: '',
  responseType: '',
  responseURL: '',
  status: 0,
  statusText: '',
  timeout: 0,
  upload:
   XMLHttpRequestUpload {
     onloadstart: null,
     onprogress: null,
     onabort: null,
     onerror: null,
     onload: null,
     ontimeout: null,
     onloadend: null,
     _listeners: {},
     _request: [Circular],
     _contentType: 'text/plain;charset=UTF-8',
     _body: <Buffer hidden budy... > },
  _method: 'POST',
  _url:
   Url {
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'ropsten.infura.io',
     port: null,
     hostname: 'ropsten.infura.io',
     hash: null,
     search: null,
     query: null,
     pathname: '/<hidden key>',
     path: '/<hidden key>',
     href: 'https://ropsten.infura.io/<hidden key>' },
  _sync: false,
  _headers:
   { 'Content-Type': 'application/json',
     Connection: 'keep-alive',
     Host: 'ropsten.infura.io',
     'User-Agent': '<hidden machine information>',
     'Content-Length': '98' },
  _loweredHeaders: { 'content-type': 'Content-Type' },
  _mimeOverride: null,
  _request: null,
  _response: null,
  _responseParts: null,
  _responseHeaders: null,
  _aborting: null,
  _error: null,
  _loadedBytes: 0,
  _totalBytes: 0,
  _lengthComputable: false }

```

```
TypeError: JSON.decycle is not a function
    at Object.InvalidResponse (/Users/xxx/ws/boba/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:36:153)
    at XMLHttpRequest.request.onreadystatechange (/Users/xxx/ws/boba/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:117:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/xxx/ws/boba/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/xxx/ws/boba/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/xxx/ws/boba/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/xxxd/ws/boba/node_modules/xhr2/lib/xhr2.js:414:24)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by xinbenlv** [comment]
changing `https://ropsten.infura.io/<hidden key>` to `https://ropsten.infura.io/v3/<hidden key>` still have the same problem

**Comment by Anthalasath** [comment]
Having similar issue here, trying to deploy to rinkeby and using Infura as provider as well. Connecting to Kovan seems to work properly. 
(I also seem to get sometimes JSON RPC error while trying to connect to mainnet, but as the time of writing, connecting to mainnet seems to work again).
Not sure if this is related to truffle-hdwallet-provider or infura itself.

**Comment by DavidVotrubec** [comment]
I have the same problem

**Comment by xilibi2003** [comment]
Sometimes  this problem show if gas low, so check the gas and gasPrice

**Comment by mlekena** [comment]
For me, this problem occurred because the link I was using for Infura had an incorrect security token. Basically, the linked to the blockchain was wrong.

Dont be me, be better :rofl:
