### ISSUE TITLE
npm install truffle-hdwallet-provider install  fail

### ISSUE THREAD

**Issue by lpwlpw** [trufflesuite/truffle-hdwallet-provider#52]
npm install truffle-hdwallet-provider

scrypt@6.0.3 preinstall /Users/LPW/node_modules/scrypt
node node-scrypt-preinstall.js

scrypt@6.0.3 install /Users/LPW/node_modules/scrypt
node-gyp rebuild

SOLINK_MODULE(target) Release/copied_files.node
CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
LIBTOOL-STATIC Release/scrypt_wrapper.a
libtool: unrecognized option -static' libtool: Trylibtool --help' for more information.
make: * [Release/scrypt_wrapper.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/LPW/node_modules/scrypt
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN LPW@1.0.0 No description
npm WARN LPW@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kenntinio** [comment]
is this now fix?

**Comment by 0xMishell** [comment]
Node v12.4.0
npm 6.9.0
Truffle v5.0.24 (core: 5.0.24)
Log: 
8189 error errno 1
8190 error scrypt@6.0.3 install: `node-gyp rebuild`
8190 error Exit status 1
8191 error Failed at the scrypt@6.0.3 install script.
8191 error This is probably not a problem with npm. There is likely additional logging output above.
8192 verbose exit [ 1, true ]

How to solve it?

**Comment by JoshuaBrown** [comment]
I fixed by switching to node 11.15.0.  Install will fail on a version > 12

**Comment by largo87** [comment]
trying to install truffle-hdwallet-provider using node v 10.16.0 but is fail
