### ISSUE TITLE
Error: Command failed: cd client && npm install && npm run link-contracts

### ISSUE THREAD

**Issue by michelle2222** [trufflesuite/truffle-hdwallet-provider#71]
Hi,
I'm trying to unbox the react truffle box, and I keep getting this error. I've uninstalled and reinstalled truffle and node.js (also a bunch of other "solutions"), which didn't work. Any idea why I keep getting this error?

C:\Users\mforr\Documents\University\UQ\DECO7860 Masters Thesis\credentia-dapp>truffle unbox react
Downloading...
Unpacking...
Setting up...
Error: Command failed: cd client && npm install && npm run link-contracts
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mforr\Documents\University\UQ\DECO7860 Masters Thesis\credentia-dapp\client\node_modules\keccak
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mforr\AppData\Roaming\npm-cache\_logs\2018-09-25T08_20_37_484Z-debug.log
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mforr\Documents\University\UQ\DECO7860 Masters Thesis\credentia-dapp\client\node_modules\scrypt
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mforr\AppData\Roaming\npm-cache\_logs\2018-09-25T08_20_42_671Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by jaebooker** [comment]
Same issue. Hopefully Truffle will have some answers.

**Comment by Adrianf23** [comment]
Similar issue. I may be able to help. 

1. Make sure you uninstall Python 3.x.x and downgrade to a 2.x.x and remove python 3.x.x. from the path if you had to uninstall it. 
2. Follow the instructions found [here](https://github.com/nodejs/node-gyp) on the node-gyp github page. Specifically:

> Install all the required tools and configurations using Microsoft's [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) using `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).

To navigate the powershell as an admin: 
`Set-Location -Path C:\Path\To\Empty\Directory -PassThru `

-PassThru lets you cjeck that you are in the directory you stated

Then try running `truffle unbox react`. Everything should work now.

**Comment by Adrianf23** [comment]
Similar issue. I may be able to help. 

1. Make sure you uninstall Python 3.x.x and downgrade to a 2.x.x version. Remove python 3.x.x. from the [Path](https://www.digitalcitizen.life/how-edit-or-delete-environment-variables-windows-7-windows-8) (not the PATHTEXT) if you had to uninstall it. 
2. Follow the instructions found [here](https://github.com/nodejs/node-gyp) on the node-gyp github page. Specifically:

> Install all the required tools and configurations using Microsoft's [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) using `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).

To navigate the PowerShell as an admin: 
`Set-Location -Path C:\Path\To\Empty\Directory -PassThru `

-PassThru lets you check that you are in the directory you stated

Then try running `truffle unbox react`. Everything should work now.

**Comment by karadikid** [comment]
Any solution here?  Bump

**Comment by prakashujjwal1010** [comment]
same issue here.
sudo truffle unbox react
This directory is non-empty...
? Proceed anyway? Yes
✔ Preparing to download box
✔ Downloading
client already exists in this directory...
? Overwrite client? Yes
contracts already exists in this directory...
? Overwrite contracts? Yes
migrations already exists in this directory...
? Overwrite migrations? Yes
test already exists in this directory...
? Overwrite test? Yes
sh: 1: cannot create builderror.log: Permission denied
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/secp256k1/build'
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/secp256k1
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pudio/.npm/_logs/2019-12-30T13_21_11_221Z-debug.log
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/keccak/build'
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/keccak
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@2.0.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@2.0.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pudio/.npm/_logs/2019-12-30T13_21_12_579Z-debug.log
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/sha3/build'
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/sha3
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pudio/.npm/_logs/2019-12-30T13_21_13_293Z-debug.log
✔ cleaning up temporary files
✖ Setting up box
✖ Setting up box
Error: Command failed: cd client && npm ci
sh: 1: cannot create builderror.log: Permission denied
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/secp256k1/build'
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/secp256k1
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pudio/.npm/_logs/2019-12-30T13_21_11_221Z-debug.log
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/keccak/build'
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/keccak
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@2.0.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@2.0.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pudio/.npm/_logs/2019-12-30T13_21_12_579Z-debug.log
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/sha3/build'
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pudio/Documents/atomprojects/TenderDapp/client/node_modules/sha3
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pudio/.npm/_logs/2019-12-30T13_21_13_293Z-debug.log

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:107:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:61:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.1.6 (core: 5.1.6)
Node v12.14.0


tried to reinstall truffle, nodejs , tried to install nodejs using nvm, tried to install trufle using sudo using --unsafe-perm,... but still getting the error.
anybody can help? please.

**Comment by devang1116** [comment]
Try using this command to unbox :
truffle unbox LibertyLocked/truffle-react-ts-template

**Comment by LuckayBoy** [comment]
Hello I have the same problem and Ir what I have when I using this command : truffle unbox LibertyLocked/truffle-react-ts-template



PS C:\Users\Luckay\TokenV1> truffle unbox LibertyLocked / truffle-react-ts-template
Error: EPERM: operation not permitted, mkdir 'C:\'
    at Object.mkdirSync (fs.js:1009:3)
    at Object.module.exports.makeDirSync (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\fs-extra\lib\mkdirs\make-dir.js:101:1)
    at Object.run (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\unbox.js:54:1)
    at Command.run (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:147:1)
    at Object.586806 (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\cli.js:51:1)
    at __webpack_require__ (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:18:1)
    at __webpack_require__.x (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:36:1)
    at Function.__webpack_require__.x (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\runtime\startup chunk dependencies:35:1)
    at C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\startup:3:1
    at Object.<anonymous> (C:\Users\Luckay\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:633:12)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Truffle v5.3.6 (core: 5.3.6)
Node v14.17.0
