### ISSUE TITLE
web3one.3 Mnemonic invalid or undefined

### ISSUE THREAD

**Issue by thegostep** [trufflesuite/truffle-hdwallet-provider#82]
My truffle v5.0.0-beta.2 migration fails to deploy to rinkeby infura API.

The issue seems to be from not correctly processing the mnemonic.

Here is my .env file setup with a sample mnemonic and removed API key.

```
MNEMONIC="prevent indoor veteran upgrade salad limit prefer sausage december write giggle battle wisdom remind giant"
INFURA_API_KEY="###"
```

Here is my truffle.js setup.

```
require('dotenv').config();
const HDWalletProvider = require("truffle-hdwallet-provider");

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    },
    rinkeby: {
      provider: () => new HDWalletProvider(process.env.MNENOMIC, "https://rinkeby.infura.io/v3/" + process.env.INFURA_API_KEY),
      network_id: 4,
      gas: 3000000,
      gasPrice: 21
    }
  },
  compilers: {
     solc: {
       version: "0.4.24"
     }
  }
};
```

Here are my dependencies.

```
"dependencies": {
    "bn.js": "^4.11.8",
    "dotenv": "^6.2.0",
    "ganache-cli": "^6.2.3",
    "openzeppelin-solidity": "^2.0.0",
    "truffle": "^5.0.0-beta.2",
    "truffle-hdwallet-provider": "^1.0.0-web3one.3"
  }
```

Here is my error.

```
$ truffle migrate --network rinkeby
Error: Mnemonic invalid or undefined
    at new v (/Users/###/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-pr
ovider/src/index.js:51:1)
    at Object.provider (/Users/###/truffle.js:14:23)
    at Object.create (/Users/###/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-provider/index.js:15:

1)
    at Config.get [as provider] (/Users/###/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-config/ind
ex.js:208:1)
    at Object.detect (/Users/###/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-core/lib/environment.
js:58:1)
    at Object.<anonymous> (/Users/###/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command
s/migrate.js:170:1)
    at cb (util.js:368:39)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by gnidan** [comment]
Sounds like this is resolved: https://gitter.im/ConsenSys/truffle?at=5c115bfb8d4f3a2a7cb042de

**Comment by JimLynchCodes** [comment]
I am getting this same error. It all of the sudden started happening even though my .env file has no changes... what's the solution? 🤔
