### ISSUE TITLE
truffle compile , Error: Error: Cannot find module 'websocket'  

### ISSUE THREAD

**Issue by sowmyakannan** [trufflesuite/truffle-hdwallet-provider#83]
I upgraded Truffle, then did a new install for truffle-hdwallet-provider using the following command:

$ npm install truffle-hdwallet-provider.

Now when I run truffle compile i get an error saying this:

Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at require (/home/sowmya.kannan/equitativa/blockchain/development/gitprojects/exchange.property/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/home/sowmya.kannan/equitativa/blockchain/development/gitprojects/exchange.property/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:1:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/sowmya.kannan/equitativa/blockchain/development/gitprojects/exchange.property/truffle.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.Config.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:381:1)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:370:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/compile.js:47:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:65:1
Truffle v5.0.0 (core: 5.0.0)
Node v11.4.0
----------------------------------------------------------------------------------------------------------------------------------

Any inputs on how to fix this would be appreciated.

**Comment by yasmineSidhom** [comment]
I have this problem too (with truffle test). Does anyone has a solution ?
Thanks

**Comment by yasmineSidhom** [comment]
I have this problem too (with truffle test). Does anyone have a solution ?
