### ISSUE TITLE
Truffle cannot find any-promise

### ISSUE THREAD

**Issue by raisty** [trufflesuite/truffle-hdwallet-provider#85]
Truffle cannot find any-promise.

Reproduction:

```
npm install truffle-hdwallet-provider --save-dev
```

```
Error: Cannot find module 'any-promise'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at require (/Users/falcooon/solidity/stable/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/Users/falcooon/solidity/stable/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:1:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/falcooon/solidity/stable/truffle-config.js:1:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Function.Config.load (/Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:381:1)
    at Function.Config.detect (/Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:370:1)
    at Object.run (/Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/compile.js:47:1)
    at Command.run (/Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
    at __webpack_require__ (/Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:19:1)
    at /Users/falcooon/.nvm/versions/node/v8.3.0/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:65:1
Truffle v5.0.0 (core: 5.0.0)
Node v8.3.0
```

Temporary fix with:
```
npm install any-promise --save-dev
npm install bindings --save-dev
```

Fix please 🐐

**Comment by wfoster232** [comment]
Also hit this issue today with truffle-hdwallet-provider version **1.0.0-web3one.5**

**Extract from package-lock.json**
`"truffle-hdwallet-provider": {
      "version": "1.0.0-web3one.5",
      "resolved": "https://registry.npmjs.org/truffle-hdwallet-provider/-/truffle-hdwallet-provider-1.0.0-web3one.5.tgz",
      "integrity": "sha512-mALnG1ahfqPFufwzNcxW6JxSzgP+FwSyHr8kFtBE/ymMH8N6S2EeUPFds7a2IKyTMZ3npTMHLTR+seTQitn2yQ=="
    }`

**work-around: Adding any-promise directly as a dependency into package.json worked for us too**
